name: Build
on:
  push:
    branches:
      - main
      - develop
      - 'release-**'
      - 'hotfix-**'
    paths-ignore:
      - .github/**
  pull_request:
  workflow_dispatch:

jobs:
########################
# Build
########################
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix:
        gradle-version: [current, release-candidate]
        include:
          - java-version: 17
            gradle-version: current
          - java-version: 17
            gradle-version: release-candidate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # AdoptOpenJDK

      - name: Build with Gradle
        id: setup-gradle
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - name: Dry Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        run: gradle build --dry-run
      
      - name: Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        run: gradle build --stacktrace
      
      - name: Version used
        shell: bash
        run: echo "The version was ${{ steps.setup-gradle.outputs.gradle-version }}"
      
      - name: Publish to Nexus Repository
        shell: bash
        env:
          NEXUS_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_URL }}/repository/maven-releases/'
        run: gradle publish -PnexusRepositoryUrl=${NEXUS_REPOSITORY_URL}