name: Build
on:
  push:
    branches:
      - main
      - develop
      - 'release-**'
      - 'hotfix-**'
    paths-ignore:
      - .github/**
  pull_request:
  workflow_dispatch:

jobs:
########################
# Build
########################
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix:
        gradle-version: [current, release-candidate]
        include:
          - java-version: 17
            gradle-version: current
          - java-version: 17
            gradle-version: release-candidate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # AdoptOpenJDK

      - name: Build with Gradle
        id: setup-gradle
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - name: Dry Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        run: gradle build --dry-run
      
      - name: Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        run: gradle clean assemble
      
      - name: Version used for build
        shell: bash
        run: echo "The version was ${{ steps.setup-gradle.outputs.gradle-version }}"

      - name: Publish to Nexus Repository
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          serverUrl: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
          groupId: 'network.arkane.blockchain-providers'
          artifactId: 'litecoinj'
          version: '0.17-SNAPSHOT'
          repository: 'maven-snapshots' # or 'maven-snapshots' based on your use case
          assets: |
            target/core/build/libs/litecoinj-core-0.17-SNAPSHOT-javadoc.jar
            target/core/build/libs/litecoinj-core-0.17-SNAPSHOT-sources.jar
            target/core/build/libs/litecoinj-core-0.17-SNAPSHOT.jar



