name: Build
on:
  push:
    branches:
      - main
      - develop
      - 'release-**'
      - 'hotfix-**'
    paths-ignore:
      - .github/**
  pull_request:
  workflow_dispatch:

jobs:
########################
# Build
########################
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix:
        gradle-version: [8.4]
        include:
          - java-version: 17
            gradle-version: 8.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # AdoptOpenJDK

      - name: Build with Gradle
        id: setup-gradle
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
          NEXUS_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - name: Dry Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        env:
          NEXUS_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: gradle build --dry-run
      
      - name: Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        env:
          NEXUS_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: gradle clean assemble --stacktrace
      
      # - name: Publish to Nexus Repository
      #   shell: bash
      #   env:
      #     NEXUS_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      #     NEXUS_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      #   run: gradle publish --stacktrace

      - name: Version used for build
        shell: bash
        run: echo "The version was ${{ steps.setup-gradle.outputs.gradle-version }}"
      
      - name: Debug
        shell: bash
        run: |
          ls
          pwd
      
      - name: Publish to Nexus Repository
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          serverUrl: https://pkg.arkane.network/repository/maven-private-snapshots/
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
          coordinates: groupId=arkane-snapshots artifactId=litecoinj version=0.17-SNAPSHOT
          assets: |
            extension=jar filename=core/build/libs/litecoinj-core-0.17-SNAPSHOT-javadoc.jar
            extension=jar filename=core/build/libs/litecoinj-core-0.17-SNAPSHOT-sources.jar
            extension=jar filename=core/build/libs/litecoinj-core-0.17-SNAPSHOT.jar
          format: maven2
          repository: 'maven-snapshots'
          filename: core/build/libs/litecoinj-core-0.17-SNAPSHOT.jar


