name: Build
on:
  push:
    branches:
      - main
      - develop
      - 'release-**'
      - 'hotfix-**'
    paths-ignore:
      - .github/**
  pull_request:
  workflow_dispatch:

jobs:
########################
# Build
########################
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix:
        gradle-version: [current, release-candidate]
        include:
          - java-version: 17
            gradle-version: current
          - java-version: 17
            gradle-version: release-candidate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # AdoptOpenJDK

      - name: Build with Gradle
        id: setup-gradle
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - name: Dry Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        run: gradle build --dry-run
      
      - name: Run with Gradle version ${{ matrix.gradle-version }}
        shell: bash
        run: gradle clean assemble
      
      - name: Version used for build
        shell: bash
        run: echo "The version was ${{ steps.setup-gradle.outputs.gradle-version }}"

      - name: Capture JAR filenames
        id: capture_jars
        shell: bash
        run: |
          echo "LITECOINJ_CORE_JAVADOC=$(ls core/build/libs/*-javadoc.jar)" >> $GITHUB_ENV
          echo "LITECOINJ_CORE_SOURCES=$(ls core/build/libs/*-sources.jar)" >> $GITHUB_ENV
          echo "LITECOINJ_CORE_JAR=$(ls core/build/libs/*[^-sources].jar)" >> $GITHUB_ENV
      
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
          format: maven2
          repository: maven-releases
          assets: |
            extension=jar;filename=${{ env.LITECOINJ_CORE_JAVADOC }}
            extension=jar;filename=${{ env.LITECOINJ_CORE_SOURCES }}
            extension=jar;filename=${{ env.LITECOINJ_CORE_JAR }}